apiVersion: batch/v1
kind: Job
metadata:
  name: llm-systems
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/gpu.product
                  operator: In
                  values:
                    - NVIDIA-A25
                    - NVIDIA-A40

      tolerations:
        - effect: NoSchedule
          key: nautilus.io/nrp-testing
          operator: Exists
      containers:
        - name: rsmt-gpu
          image: subhasis79/llm-fastchat:latest
          env:
            - name: 'model_name'
              value: "meta-llama/Llama-3.1-70B"
          command: ["/bin/sh", "-c"]
          args: ["sleep 18000;                      
             
          "]

          resources:
            limits:
              memory: 50Mi
              cpu: 50m
              

            requests:
              memory: 50Mi
              cpu: 50m
              

          volumeMounts:
             - mountPath: /datavol
               name: datavol
      volumes:
         - name: datavol
           persistentVolumeClaim:
             claimName:  llama-model-pvc
      restartPolicy: Never
  backoffLimit: 3