apiVersion: batch/v1
kind: Job
metadata:
  name: llm-systems-fsc
spec:
  template:
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       # - matchExpressions:
      #       #   - key: topology.kubernetes.io/region
      #       #     operator: In
      #       #     values:
      #       #     - us-west

      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-A10"
      
      containers:
        - name: finetune-gpu
          image: pytorch/pytorch:2.7.0-cuda11.8-cudnn9-runtime
          env:
            - name: 'model_name'
              value: "meta-llama/Llama-3.1-70B"
          command: ["/bin/sh", "-c"]
          args: ["sleep 18000;                      
             
          "]

          resources:
            limits:
              memory: 32Gi
              cpu: 4 
              nvidia.com/gpu: "1"
              

            requests:
              memory: 32Gi
              cpu: 4
              nvidia.com/gpu: "1"
              

          volumeMounts:
             - mountPath: /datavol
               name: datavol
      volumes:
         - name: datavol
           persistentVolumeClaim:
             claimName:  adil-pvc
      restartPolicy: Never
  backoffLimit: 3