apiVersion: apps/v1
kind: Job
metadata:
  name: llm-systems
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: mypod
        image: subhasis79/llm-cuda:1.0
        resources:
          limits:
            memory: 128Gi
            cpu: "8"
            nvidia.com/gpu: "0"
          requests:
            memory: 128Gi
            cpu: "8"
            nvidia.com/gpu: "0"
        volumeMounts:
          - mountPath: "/mnt/storage"
            name: storage-volume
          - mountPath: "/dev/shm"
            name: dshm
        command: [ "sh", "-c", "/usr/sbin/sshd && echo 'I'\\''m a new pod with GPUs and storage' && sleep infinity" ]
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: adil-pvc
        - name: dshm
          emptyDir:
            medium: Memory
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      # nodeSelector:
      #   nvidia.com/gpu.product: "NVIDIA-A100"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/region
      #           operator: In
      #           values:
      #           - us-west