apiVersion: batch/v1
kind: Job
metadata:
  name: multi-gpu-job
spec:
  template:
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       # - matchExpressions:
      #       #   - key: topology.kubernetes.io/region
      #       #     operator: In
      #       #     values:
      #       #     - us-west

      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      # nodeSelector:
      #   nvidia.com/gpu.product: "NVIDIA-A10"
      
      containers:
        - name: finetune-gpu
          image: subhasis79/pytorch-cuda-12-devel:1.1
          env:
            - name: 'model_name'
              value: "meta-llama/Llama-3.1-70B"
          command: ["/bin/sh", "-c"]
          args: [" sleep 180000;
                    cd /datavol/deepspeed;
                    deepspeed --num_gpus=2 train_qwen_lora_ds.py;
                                      
             
          "]

          resources:
            limits:
              memory: 32Gi
              cpu: 2 
              nvidia.com/mig-small : "1"
              

            requests:
              memory: 32Gi
              cpu: 2
              nvidia.com/mig-small: "1"
              

          volumeMounts:
             - mountPath: /datavol
               name: datavol
             
      volumes:
         - name: datavol
           persistentVolumeClaim:
             claimName:  adil-pvc
        
      restartPolicy: Never
  backoffLimit: 3